version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
  api:
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 #by default, 6379 is the port exposed by redis instance
      - PGUSER=postgres #default postgres user
      - PGHOST=postgres
      - PGDATABASE=postgres #default database of postgres
      - PGPASSWORD=postgres_password #default password for postgres
      - PGPORT=5432 #from dockerhub documentation for postgres image
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker/
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app